SELECT DISTINCT(crcc.CAR_ID)
FROM CAR_RENTAL_COMPANY_CAR crcc
INNER JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY on CAR_RENTAL_COMPANY_RENTAL_HISTORY.CAR_ID = crcc.CAR_ID
WHERE MONTH(START_DATE) = 10 AND CAR_TYPE='세단'
ORDER BY CAR_ID DESC;