SELECT 
    ITEM_TREE.ITEM_ID, 
    (SELECT ITEM_NAME FROM ITEM_INFO WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID) AS ITEM_NAME, 
    (SELECT RARITY FROM ITEM_INFO WHERE ITEM_INFO.ITEM_ID = ITEM_TREE.ITEM_ID) AS RARITY 
FROM 
    ITEM_INFO 
INNER JOIN 
    ITEM_TREE ON ITEM_INFO.ITEM_ID = ITEM_TREE.PARENT_ITEM_ID 
WHERE 
    ITEM_INFO.RARITY = 'RARE' 
ORDER BY 
    ITEM_TREE.ITEM_ID DESC;
